### ISSUE TITLE
Generated tags contain intero temporary files

### ISSUE THREAD

**Issue by inflation** [grwlf/haskdogs#2]
Hi, I'm using `intero` for auto-completion and syntax checking. The program will write temporary source code under the folder `.stack-work/intero`, which I don't want them to appear in the tags. Currently, I couldn't find an option to exclude folders or files. 

It would be great if you could exclude the folder by default and also provide an option for flexibility. Thank you.

**Comment by sergei-mironov** [comment]
Hi. Thanks for the report. Could you please check the new `--raw` mode from master? Consider using it like this:

    haskdogs --raw | grep -v .stack-work | hasktags -c -x STDIN

**Comment by sergei-mironov** [comment]
Closing for now, please reopen if it is still a problem
