### ISSUE TITLE
Argument list is too long for big project.

### ISSUE THREAD

**Issue by yihuang** [grwlf/haskdogs#3]
The error happens when calling ``hasktags -c -x a-long-list-of-files``, and the list is more than 400kilobytes.
The full log is:
```
...
> hasktags -c -x ...
haskdogs: hasktags: readCreateProcess: runInteractiveProcess: exec: resource exhausted (Argument list too long)
```

**Comment by sergei-mironov** [comment]
Could you please provide the exact error message? Did you try to use `--dir-list` or `--file-list` options to make haskdogs read input from files?

**Comment by yihuang** [comment]
@grwlf Thanks for the reply, I've added more details in the question.
I find ``hasktags`` has an option to read file list from stdin, maybe we should use that.
I tried to save the file list to a file one line per file name, and run:
```
hasktags -c -x STDIN < /tmp/filelist
```
It works well.

**Comment by sergei-mironov** [comment]
Thanks, I've understood the problem. Could you please check https://hackage.haskell.org/package/haskdogs-0.5.3 or latest master ?

**Comment by yihuang** [comment]
Yeah, it works now.
